# Generated by Django 3.2 on 2023-05-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Linea_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=100, verbose_name='Linea')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.CharField(max_length=10, verbose_name='Cod. Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('pcio_lista', models.FloatField(max_length=20, verbose_name='Precio de Lista')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('imagen', models.CharField(max_length=10, null=True, verbose_name='Imagen')),
                ('linea', models.CharField(max_length=100, verbose_name='Linea')),
                ('rubro', models.CharField(max_length=50, verbose_name='Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('pcio_lista', models.FloatField(max_length=10, verbose_name='Precio')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.linea_servicio')),
            ],
        ),
    ]
